theme: jekyll-theme-minimal
logo: logo.png
title: GNU/Linux Pro
description: Про GNU/Linux и IT
github:
  repository_url: https://github.com/gnulinuxpro/
  youtube_url: https://www.youtube.com/channel/UCbi6BvrrHU5Ppct4x_dVP2Q 